"""Core data models for the trading bot.

All domain objects are defined here to ensure consistency across modules.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Any, Literal


@dataclass
class TradeSignal:
    """Trade signal generated by strategy or decision engine."""
    symbol: str
    direction: Literal["BUY", "SELL"]
    entry_price: float
    sl: float
    tp: float
    lot_size: float
    timestamp: datetime = field(default_factory=datetime.now)
    strategy: str = "Unknown"
    ai_score: Optional[int] = None
    regime: Optional[str] = None


@dataclass
class Position:
    """Open position representation."""
    ticket: int
    symbol: str
    position_type: Literal["BUY", "SELL"]
    volume: float
    open_price: float
    sl: float
    tp: float
    profit: float = 0.0
    swap: float = 0.0
    open_time: datetime = field(default_factory=datetime.now)
    magic_number: int = 234000


@dataclass
class AccountInfo:
    """Account information snapshot."""
    balance: float
    equity: float
    margin: float
    free_margin: float
    margin_level: float
    currency: str = "USD"
    leverage: float = 100.0


@dataclass
class SignalOutput:
    """Raw signal from regime pipeline."""
    action: str
    confidence: int
    regime: str
    strategy: str
    expected_pf: float
    expected_max_dd: float
    expected_avg_rr: float
    consistency_score: int
    sl: float
    tp: float
    entry: float
    lot_size: float
    explanation: str
    metrics: Dict[str, Any]
    ml_confidence: Optional[float] = None


@dataclass
class Decision:
    """Final gated decision from the decision engine."""
    action: Literal["BUY", "SELL", "NO_TRADE"]
    ai_score: int
    regime_signal: SignalOutput
    smc: Any  # SMCResult - avoid circular import
    confluence_notes: List[str] = field(default_factory=list)
    explanation: str = ""
    sl: float = 0.0
    tp: float = 0.0
    entry: float = 0.0
    lot_size: float = 0.0


@dataclass
class DailyGuardStatus:
    """Status from daily risk guard."""
    should_block_new_trades: bool
    should_close_all: bool
    daily_pnl_pct: float
    reason: str
    # Stable machine-readable identifier for which guard produced `reason`
    # (e.g. "max_consecutive_losses", "daily_loss_limit", "daily_profit_lock").
    # Empty string when no guard is triggered. Additive field for diagnostics;
    # existing callers that only read the other fields are unaffected.
    guard_name: str = ""


@dataclass
class HealthStatus:
    """System health status snapshot."""
    connected: bool
    symbol: Optional[str]
    terminal_ok: bool
    account_ok: bool
    checked_at: datetime
    uptime_seconds: float
    last_market_data_update: Optional[datetime] = None
    last_successful_trade: Optional[Dict[str, Any]] = None
    last_error: Optional[Dict[str, Any]] = None
    last_order: Optional[Dict[str, Any]] = None


@dataclass
class SMCResult:
    """Smart Money Concepts analysis result."""
    swings: List[Any] = field(default_factory=list)
    structure_events: List[Any] = field(default_factory=list)
    order_blocks: List[Any] = field(default_factory=list)
    fvgs: List[Any] = field(default_factory=list)
    liquidity_sweeps: List[Any] = field(default_factory=list)
    equal_levels: List[Any] = field(default_factory=list)
    zone: Literal["premium", "discount", "equilibrium"] = "equilibrium"
    bias: Literal["bullish", "bearish", "neutral"] = "neutral"


@dataclass
class BacktestSummary:
    """Backtest performance summary."""
    final_balance: float
    return_pct: float
    trades: int
    wins: int
    win_rate: float
    profit_factor: float
    max_dd: float
    equity_curve: List[float]
    regime_breakdown: Dict[str, Any]
    # Additive/optional: populated only when the backtest engine is asked to
    # track guard behavior (see BacktestEngine.run(track_guard_diagnostics=)).
    # Empty dict otherwise; existing callers are unaffected.
    guard_diagnostics: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MonteCarloReport:
    """Monte Carlo simulation report."""
    n_simulations: int
    method: str
    starting_balance: float
    seed: Optional[int]
    n_trades: int
    sim_size: int
    returns_pct: List[float] = field(default_factory=list)
    final_balances: List[float] = field(default_factory=list)
    return_stats: Dict[str, float] = field(default_factory=dict)
    max_dd_pct_per_sim: List[float] = field(default_factory=list)
    worst_drawdown_pct: float = 0.0
    average_drawdown_pct: float = 0.0
    confidence_intervals: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    probability_of_loss_pct: float = 0.0
    risk_of_ruin_pct: float = 0.0
    ruin_threshold_pct: float = 50.0
    sample_equity_curves: Dict[str, List[float]] = field(default_factory=dict)


@dataclass
class NewsSentiment:
    """Aggregated news sentiment for a symbol."""
    score: float = 0.0          # -1.0 (very bearish) to +1.0 (very bullish)
    label: str = "neutral"      # bearish / neutral / bullish
    article_count: int = 0
    headlines: List[str] = field(default_factory=list)
    source: str = "none"        # "alpha_vantage" or "none" (fallback)


@dataclass
class AIAnalysis:
    """Result of Claude-based market analysis."""
    confidence: Optional[float] = None   # 0-100, None if unavailable
    reasoning: str = ""
    available: bool = False
    error: Optional[str] = None
